name: "ecommerce_data_reliability_platform"
version: "1.0.0"
config-version: 2

profile: "ecommerce_data_reliability_platform"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ecommerce_data_reliability_platform:
    staging:
      +schema: silver
      +materialized: view
    gold:
      +schema: gold
      +materialized: table
